<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NROUT-LP" failures="5" tests="8" name="smokeTest.SanityTest" time="1539.121" errors="0" timestamp="17 Dec 2024 05:25:16 GMT">
  <testcase classname="smokeTest.SanityTest" name="QIDM_154_ManageTagsSmokeTests" time="76.360">
    <failure message="Error in QIDM_154_ManageTagsSmokeTests" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error in QIDM_154_ManageTagsSmokeTests
	at org.testng.Assert.fail(Assert.java:83)
	at smokeTest.SanityTest.QIDM_154_ManageTagsSmokeTests(SanityTest.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.click()" because the return value of "smokeTest.QIDM_154_ManageTagsSmokeTests.getWebElementXpath(String)" is null
	at smokeTest.QIDM_154_ManageTagsSmokeTests.manageTagsSmokeTests(QIDM_154_ManageTagsSmokeTests.java:35)
	at smokeTest.SanityTest.QIDM_154_ManageTagsSmokeTests(SanityTest.java:93)
	... 22 more
]]>
    </failure>
  </testcase> <!-- QIDM_154_ManageTagsSmokeTests -->
  <testcase classname="smokeTest.SanityTest" name="QIDM_152_DashboardAndWidgetSmokeTests" time="398.577">
    <failure message="Error in QIDM_152_DashboardAndWidgetSmokeTests" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error in QIDM_152_DashboardAndWidgetSmokeTests
	at org.testng.Assert.fail(Assert.java:83)
	at smokeTest.SanityTest.QIDM_152_DashboardAndWidgetSmokeTests(SanityTest.java:75)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//gridster[1]/gridster-item[1]/ra-widget-container[1]/div[1]/div[2]/div[2]/div[1]/pam-load-profile-widget[1]//*[contains(@class,'highcharts-legend-item highcharts-line-series highcharts-color-undefined highcharts-series-0')]/span"}
  (Session info: chrome=131.0.6778.140)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [66c9652be334a996a431f7ffe83707c8, findElement {using=xpath, value=//gridster[1]/gridster-item[1]/ra-widget-container[1]/div[1]/div[2]/div[2]/div[1]/pam-load-profile-widget[1]//*[contains(@class,'highcharts-legend-item highcharts-line-series highcharts-color-undefined highcharts-series-0')]/span}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.140, chrome: {chromedriverVersion: 131.0.6778.108 (3b014839fbc..., userDataDir: C:\Users\nrout\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55205}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:55205/devtoo..., se:cdpVersion: 131.0.6778.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 66c9652be334a996a431f7ffe83707c8
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:356)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at smokeTest.QIDM_152_DashboardAndWidgetSmokeTests.dashboardAndWidgetSmokeTests(QIDM_152_DashboardAndWidgetSmokeTests.java:95)
	at smokeTest.SanityTest.QIDM_152_DashboardAndWidgetSmokeTests(SanityTest.java:71)
	... 22 more
]]>
    </failure>
  </testcase> <!-- QIDM_152_DashboardAndWidgetSmokeTests -->
  <testcase classname="smokeTest.SanityTest" name="QIDM_148_CalendarLoadProfileAnalysisSmokeTest" time="123.007">
    <failure message="Error in QIDM_148_CalendarLoadProfileAnalysisSmokeTest" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error in QIDM_148_CalendarLoadProfileAnalysisSmokeTest
	at org.testng.Assert.fail(Assert.java:83)
	at smokeTest.SanityTest.QIDM_148_CalendarLoadProfileAnalysisSmokeTest(SanityTest.java:42)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at smokeTest.QIDM_148_CalendarLoadProfileAnalysisSmokeTest.calendarLoadProfileAnalysisSmokeTest(QIDM_148_CalendarLoadProfileAnalysisSmokeTest.java:118)
	at smokeTest.SanityTest.QIDM_148_CalendarLoadProfileAnalysisSmokeTest(SanityTest.java:38)
	... 22 more
]]>
    </failure>
  </testcase> <!-- QIDM_148_CalendarLoadProfileAnalysisSmokeTest -->
  <testcase classname="smokeTest.SanityTest" name="QIDM_146_TrendAnalysisSmokeTest" time="135.874"/>
  <testcase classname="smokeTest.SanityTest" name="QIDM_153_ManageMeasurementsSmokeTests" time="480.954">
    <failure message="Error in QIDM_153_ManageMeasurementsSmokeTests" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error in QIDM_153_ManageMeasurementsSmokeTests
	at org.testng.Assert.fail(Assert.java:83)
	at smokeTest.SanityTest.QIDM_153_ManageMeasurementsSmokeTests(SanityTest.java:86)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.getText()" because the return value of "smokeTest.QIDM_153_ManageMeasurementsSmokeTests.getWebElementXpath_D(String)" is null
	at smokeTest.QIDM_153_ManageMeasurementsSmokeTests.manageMeasurementsSmokeTests(QIDM_153_ManageMeasurementsSmokeTests.java:40)
	at smokeTest.SanityTest.QIDM_153_ManageMeasurementsSmokeTests(SanityTest.java:82)
	... 22 more
]]>
    </failure>
  </testcase> <!-- QIDM_153_ManageMeasurementsSmokeTests -->
  <testcase classname="smokeTest.SanityTest" name="QIDM_147_LoadProfileAnalysisSmokeTest" time="135.195"/>
  <testcase classname="smokeTest.SanityTest" name="QIDM_151_ScatterPlotAnalysisSmokeTest" time="181.430"/>
  <testcase classname="smokeTest.SanityTest" name="QIDM_150_ComparisonAnalysisSmokeTest" time="7.724">
    <failure message="Error in QIDM_150_ComparisonAnalysisSmokeTest" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error in QIDM_150_ComparisonAnalysisSmokeTest
	at org.testng.Assert.fail(Assert.java:83)
	at smokeTest.SanityTest.QIDM_150_ComparisonAnalysisSmokeTest(SanityTest.java:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, get {url=https://core.stg1.resourceadvisor.schneider-electric.com}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.140, chrome: {chromedriverVersion: 131.0.6778.108 (3b014839fbc..., userDataDir: C:\Users\nrout\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55041}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:55041/devtoo..., se:cdpVersion: 131.0.6778.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:151)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:301)
	at common.LoginTC.login(LoginTC.java:47)
	at smokeTest.QIDM_150_ComparisonAnalysisSmokeTest.comparisonAnalysisSmokeTest(QIDM_150_ComparisonAnalysisSmokeTest.java:31)
	at smokeTest.SanityTest.QIDM_150_ComparisonAnalysisSmokeTest(SanityTest.java:49)
	... 22 more
]]>
    </failure>
  </testcase> <!-- QIDM_150_ComparisonAnalysisSmokeTest -->
</testsuite> <!-- smokeTest.SanityTest -->
